### ISSUE TITLE
add configuration for preload script. 

### ISSUE THREAD

**Issue by oSethoum** [jctaoo/electron-starter#49]
Can you please add configuration for preload script to bundle it with the app, and if you can make it in typescript it will be amazing.

**Comment by jctaoo** [comment]
Hi! If I understand you correctly, you mean you want to use context isolation.

This project supported preload script already and you can write it in typescript. Exactly, this project using another [electron-run](https://github.com/jctaoo/electron-run) to run electron application. And `electron-run` support preload script. 

You can write a `preload.ts` and save it beside your entry point script (in this starter, it's `src/main/index.ts`), and append `--preload preload.ts` to your dev command in the `package.json`.

Check more detail at [electron-run docs](https://elecrun.jctaoo.com/#options---preload-file)

**Comment by anothertempore** [comment]
The link above is down, unable to open it.

**Comment by jctaoo** [comment]
> The link above is down, unable to open it.

I can visit it (the site is deployed on GitHub Pages), or you can try https://github.com/jctaoo/electron-run/tree/main/docs#options---preload-file

**Comment by oSethoum** [comment]
@jctaoo 
Thank you for the replay and unfortunately it didn't work. 

here's a screenshot showing what I did. 

![image](https://user-images.githubusercontent.com/88779394/130334352-1bc07c66-e149-44eb-aa57-972a98e79a84.png)

**Comment by jctaoo** [comment]
> @jctaoo
> Thank you for the replay and unfortunately it didn't work.
> 
> here's a screenshot showing what I did.
> 
> ![image](https://user-images.githubusercontent.com/88779394/130334352-1bc07c66-e149-44eb-aa57-972a98e79a84.png)

You should include `preload` option in your `webPreferences` when you create BrowserWindow, just like this:
```typescript
const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: join(__dirname, "preload.js")
    },
    show: false,
  }).once("ready-to-show", () => {
    win.show();
  });
```

**Comment by oSethoum** [comment]
@jctaoo  Thanks it worked now. 
do I have to do the same for the build command in package.json ?

**Comment by oSethoum** [comment]
@jctaoo  Thank You So Much, keep up the good work sir !
