### ISSUE TITLE
Packaging an executable ( server ) written in Go

### ISSUE THREAD

**Issue by oSethoum** [jctaoo/electron-starter#50]
I have an API written in Go, I wanna package it with the electron app and start it when the app starts. 

is there a way to do that ?

**Comment by jctaoo** [comment]
Do you have an example repository on GitHub?

**Comment by oSethoum** [comment]
@jctaoo  I have an executable that contains the business logic of the app and it expose an API ( rest API ) in order to get the data from it. 

![image](https://user-images.githubusercontent.com/88779394/133954667-d6f4d893-428c-4814-a445-a1456c9cd052.png)

This is basically what I have and and what I want to do, for now it's not working in development. 

This is the repository link : 
 https://github.com/oSethoum/Store
 
 The server starts on the port 5000 
 The API route is : 
 /users          returns and array of fake data. 
 
This is as detailed as I can get.

Thank you very much for the response ^^.
