### ISSUE TITLE
Unable to load preload script 

### ISSUE THREAD

**Issue by newonejoe** [jctaoo/electron-starter#52]
Hi jctaoo, this is really awesome tool for electron react. It's so fast compared to another vite awesome project with concurrent approach. But I am facing the preload.js issue when I am trying to use native method from electron in render process.  I took me more then 4 hours to find the root cause. I hope that you can fix it.

I go through issue [#49](https://github.com/jctaoo/vite-electron-esbuild-starter/issues/49) and [#51](https://github.com/jctaoo/vite-electron-esbuild-starter/issues/51) to fix the Unable to load preload script issue. From the document in 49, there is a point which confusing me. In issue 49, you mentioned we should add --preload preload.ts after the dev command. I followed this but still get the error.  [Thekevinbrown](https://github.com/thekevinbrown) mentioned the dev command is working. Then I git clone and test his branch and it's working! The only difference in the /src/main/index.ts is:

    `preload: join(__dirname, "preload.js")`
     #  instead of 
    `preload: join(__dirname, "preload.ts")`

preload.ts
![image](https://user-images.githubusercontent.com/7491073/136537883-34478c96-a46d-45d8-976b-474f8979cee6.png)

preload.js
![image](https://user-images.githubusercontent.com/7491073/136539035-d51edfa9-8740-4dac-84b2-4b7223a01f52.png)

**Comment by jctaoo** [comment]
The loading preload script behavior in Electron is dynamic and it’s process is in runtime instead of build time. So that the path of your preload script passed in the constructor of BrowserWindow should be runtime path. Your preload.ts will be compiled to preload.js and that’s why .js extensions works but .ts not.

**Comment by newonejoe** [comment]
> The loading preload script behavior in Electron is dynamic and it’s process is in runtime instead of build time. So that the path of your preload script passed in the constructor of BrowserWindow should be runtime path. Your preload.ts will be compiled to preload.js and that’s why .js extensions works but .ts not.

Thanks for your explanation. And maybe it's better to put the preload feature in the template
