### ISSUE TITLE
Unknown Error Occurred 

### ISSUE THREAD

**Issue by oSethoum** [jctaoo/electron-starter#54]
![image](https://user-images.githubusercontent.com/88779394/147691344-c63304b7-175a-4a63-b927-61b1830bc00b.png)

**Comment by jctaoo** [comment]
It looks like this error was thrown by [node-gyp](https://github.com/nodejs/node-gyp) when you tried to add native modules. And according to logs from node-gyp, maybe you don't set msvs correctly for node-gyp.

**Comment by oSethoum** [comment]
it was Fixed by installing the nodejs LTS version.
